kind: Secret
apiVersion: v1
metadata:
  name: {{ template "chart.fullname" . }}-secret
type: Opaque
data:
  NEW_RELIC_LICENSE_KEY: {{ .Values.newRelic.licenseKey | b64enc | quote }}
{{- if .Values.keyProtect.iamKey }}
  KEYPROTECT_SERVICE_API_KEY: {{ required "A valid .Values.keyProtect.iamKey entry required!" .Values.keyProtect.iamKey | b64enc | quote }}
{{- end }}
